Style: Minor fixes

diff --git a/smartless-recall b/smartless-recall
--- a/smartless-recall
+++ b/smartless-recall
@@ -32,7 +32,7 @@ fi
 
 recallByNumber()
 {
-    printf %s "${captures[$1 - 1]}"
+    printf %s "${captures[${1:?} - 1]}"
 }
 
 recallGrep()
@@ -46,8 +46,8 @@ case "$1" in
     *)		filespec="$(recallGrep "$@")";;
 esac
 
-if [ ! "$filespec" ]; then
-    echo >&2 "ERROR: No such captured output."
+if [ -z "$filespec" ]; then
+    echo >&2 'ERROR: No such captured output.'
     exit 1
 fi
 
